/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "date.h"

long *
bin_date_1_svc(void *argp, struct svc_req *rqstp)
{
	static long  result;

	/*
	 * insert server code here
	 */
        printf("Desde bin_date_1()");
        
        long time(); /* Función de Unix que retorna la hora */

        result = time((long *) 0);

	return &result;
}

char **
str_date_1_svc(long *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */
        printf("Desde str_date_1()");
        char *ctime(); /* Función Unix */

        result = ctime(argp); /* Convierte a la hora local */

	return &result;
}
